export enum Routes {
  About = `/about`,
  Communications = `/communications`,
  Platform = `/platform`,
  Library = `/library`,
  Trainer = `/trainer`,
  Contacts = `/contacts`,
  Identity = `/identity`,
  IdentityLogo = `/identity/logo`,
  IdentityPalette = `/identity/palette`,
  IdentityPatterns = `/identity/patterns`,
  IdentityGrid = `/identity/grid`,
  IdentityTypography = `/identity/typography`,
  IdentityPhotoStyle = `/identity/photo-style`,
  IdentityIcons = `/identity/icons`,
}
